### ISSUE TITLE
Quarkus compilation fails for basic workflow template

### ISSUE THREAD

**Issue by cmoulliard** [parodos-dev/workflow-software-templates#23]
## Issue

Quarkus compilation fails for the project - https://github.com/ch007m/onboarding created using the basic workflow template ?

```
mvn clean package quarkus:dev
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.kie.kogito:kogito-quarkus-serverless-workflow-devui:jar is missing. @ line 56, column 17
[ERROR] 'dependencies.dependency.version' for org.kie.kogito:kogito-addons-quarkus-data-index-inmemory:jar is missing. @ line 72, column 17
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.janus.workflow:onboarding:1.0.0-SNAPSHOT (/Users/cmoullia/code/kie/onboarding/pom.xml) has 2 errors
[ERROR]     'dependencies.dependency.version' for org.kie.kogito:kogito-quarkus-serverless-workflow-devui:jar is missing. @ line 56, column 17
[ERROR]     'dependencies.dependency.version' for org.kie.kogito:kogito-addons-quarkus-data-index-inmemory:jar is missing. @ line 72, column 17
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```

**Comment by pkliczewski** [comment]
@anludke please take a look

**Comment by anludke** [comment]
@cmoulliard thanks for trying this! There is an ongoing update with the kogito version which is the root cause of the compilation failure here. For the time being, please do the following:
1. change the property `kogito.bom.version` from `999-SNAPSHOT` to `2.44.0.Alpha` in this [line](https://github.com/ch007m/onboarding/blob/main/pom.xml#L16).
2. Remove or comment out the `required` field in this [file](https://github.com/ch007m/onboarding/blob/main/src/main/resources/schemas/onboarding-input-schema.json). It should be:
`{
  "$id": "classpath:/schemas/onboarding-schema.json",
  "title": "onboarding: Data Input Schema",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "onboarding__sub_schema__sample_data.json": {
      "$ref": "onboarding__sub_schema__sample_section.json",
      "type": "object"
    }
  }
}`
This will resolve the compilation issue and you should be able to execute the workflow as defined in the README

**Comment by cmoulliard** [comment]
> 2\. Remove or comment out the `required` field in the input schema in this [file](https://github.com/ch007m/onboarding/blob/main/src/main/resources/schemas/onboarding-input-schema.json).

Why should we remove the required ?

**Comment by cmoulliard** [comment]
I recompiled my project and launched it again. We got now a CORS error 

```
2024-03-15 11:37:30,753 INFO  [io.quarkus] (Quarkus Main Thread) onboarding 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.2.9.Final) started in 5.313s. Listening on: http://0.0.0.0:8080
2024-03-15 11:37:30,753 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2024-03-15 11:37:30,753 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [agroal, cache, cdi, embedded-postgres, grpc-server, hibernate-orm, hibernate-orm-panache, jackson-jq, jdbc-postgresql, kogito-addon-messaging-extension, kogito-addon-process-management-extension, kogito-addon-source-files-extension, kogito-addons-quarkus-data-index-inmemory, kogito-serverless-workflow, kogito-serverless-workflow-devui, narayana-jta, qute, reactive-routes, rest-client, rest-client-jackson, resteasy, resteasy-jackson, resteasy-multipart, security, security-properties-file, servlet, smallrye-context-propagation, smallrye-health, smallrye-openapi, smallrye-reactive-messaging, smallrye-reactive-messaging-http, swagger-ui, vertx, vertx-graphql]

2024-03-15 11:42:30,058 INFO  [io.zon.tes.db.pos.emb.EmbeddedPostgres] (postgres:pid(19736)) 2024-03-15 11:42:30.058 CET [19739] LOG:  checkpoint starting: time
2024-03-15 11:47:19,263 ERROR [io.qua.ver.htt.run.dev.DevConsoleCORSFilter] (vert.x-eventloop-thread-0) Only localhost origin is allowed, but Origin header value is: http://0.0.0.0:8080
2024-03-15 11:47:19,265 ERROR [io.qua.ver.htt.run.dev.DevConsoleCORSFilter] (vert.x-eventloop-thread-0) Only localhost origin is allowed, but Origin header value is: http://0.0.0.0:8080
2024-03-15 11:47:19,267 ERROR [io.qua.ver.htt.run.dev.DevConsoleCORSFilter] (vert.x-eventloop-thread-1) Only localhost origin is allowed, but Origin header value is: http://0.0.0.0:8080
2024-03-15 11:47:19,268 ERROR [io.qua.ver.htt.run.dev.DevConsoleCORSFilter] (vert.x-eventloop-thread-1) Only localhost origin is allowed, but Origin header value is: http://0.0.0.0:8080
```

![Screenshot 2024-03-15 at 11 47 39](https://github.com/parodos-dev/workflow-software-templates/assets/463790/158dff82-1c75-4c43-83cf-9c45e613c913)

**Comment by anludke** [comment]
> > 2. Remove or comment out the `required` field in the input schema in this [file](https://github.com/ch007m/onboarding/blob/main/src/main/resources/schemas/onboarding-input-schema.json).
> 
> Why should we remove the required ?

It's all related to the kogito version! Switching to `2.44.0.Alpha` resolves the compilation issue as you confirmed but there some fixes and enhancements part of the  `999-SNAPSHOT` that are missing. 
Indeed, this example uses a sub-schema to showcase how large data input schemas can be broken into subs for better inputs rendering in UI as steps in the [Backstage Orchestrator plugin](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/orchestrator).
I've then noticed that keeping "required" will successfully compile but the workflow execution will fail. Once the kogito version discrepancy is resolved from the dedicated team, we should be able to restore the initial data input schema setup in the template.

So, this is the error you should get if `required` is kept in the data input schema:
`❯ curl -v -X POST -H "Content-Type: application/json" http://localhost:8080/onboarding -d@input.json
* Connection #0 to host localhost left intact
{"message":"There are JsonSchema validation errors:\n$.onboarding__sub_schema__sample_data.json: is missing but it is required"}`

**Comment by anludke** [comment]
> I recompiled my project and launched it again. We got now a CORS error
> 
> ```
> 2024-03-15 11:37:30,753 INFO  [io.quarkus] (Quarkus Main Thread) onboarding 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.2.9.Final) started in 5.313s. Listening on: http://0.0.0.0:8080
> 2024-03-15 11:37:30,753 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
> 2024-03-15 11:37:30,753 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [agroal, cache, cdi, embedded-postgres, grpc-server, hibernate-orm, hibernate-orm-panache, jackson-jq, jdbc-postgresql, kogito-addon-messaging-extension, kogito-addon-process-management-extension, kogito-addon-source-files-extension, kogito-addons-quarkus-data-index-inmemory, kogito-serverless-workflow, kogito-serverless-workflow-devui, narayana-jta, qute, reactive-routes, rest-client, rest-client-jackson, resteasy, resteasy-jackson, resteasy-multipart, security, security-properties-file, servlet, smallrye-context-propagation, smallrye-health, smallrye-openapi, smallrye-reactive-messaging, smallrye-reactive-messaging-http, swagger-ui, vertx, vertx-graphql]
> 
> 2024-03-15 11:42:30,058 INFO  [io.zon.tes.db.pos.emb.EmbeddedPostgres] (postgres:pid(19736)) 2024-03-15 11:42:30.058 CET [19739] LOG:  checkpoint starting: time
> 2024-03-15 11:47:19,263 ERROR [io.qua.ver.htt.run.dev.DevConsoleCORSFilter] (vert.x-eventloop-thread-0) Only localhost origin is allowed, but Origin header value is: http://0.0.0.0:8080
> 2024-03-15 11:47:19,265 ERROR [io.qua.ver.htt.run.dev.DevConsoleCORSFilter] (vert.x-eventloop-thread-0) Only localhost origin is allowed, but Origin header value is: http://0.0.0.0:8080
> 2024-03-15 11:47:19,267 ERROR [io.qua.ver.htt.run.dev.DevConsoleCORSFilter] (vert.x-eventloop-thread-1) Only localhost origin is allowed, but Origin header value is: http://0.0.0.0:8080
> 2024-03-15 11:47:19,268 ERROR [io.qua.ver.htt.run.dev.DevConsoleCORSFilter] (vert.x-eventloop-thread-1) Only localhost origin is allowed, but Origin header value is: http://0.0.0.0:8080
> ```
> 
> ![Screenshot 2024-03-15 at 11 47 39](https://private-user-images.githubusercontent.com/463790/313162681-158dff82-1c75-4c43-83cf-9c45e613c913.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3ODQ5ODIsIm5iZiI6MTcxMDc4NDY4MiwicGF0aCI6Ii80NjM3OTAvMzEzMTYyNjgxLTE1OGRmZjgyLTFjNzUtNGM0My04M2NmLTljNDVlNjEzYzkxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxNzU4MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmE4MmRiM2FiNzg2NGIyYzZiM2RkZDMzMmUxNGU5ZDgyMjIxNzZmOTM3OWZiOTNlYjBhMWNlYzVjMGE5NGJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PhpzqyxGS8f5-uGcImMq9MHJaM3PoMRgUtigRwdF-cI)

Please try with localhost or 127.0.0.1 as provided in the README.
You should get this screen:
<img width="1743" alt="Screenshot 2024-03-18 at 1 57 43 PM" src="https://github.com/parodos-dev/workflow-software-templates/assets/15964569/ef477c2a-48c2-4035-80b6-3b4fe4c5cc10">

**Comment by cmoulliard** [comment]
Which version of Quarkus is supported as that fails using `3.8.2` 
```
 mvn clean compile quarkus:dev
...
[INFO] --- quarkus:3.8.2:dev (default-cli) @ onboarding ---
[INFO] Invoking resources:3.3.1:testResources (default-testResources) @ onboarding
[INFO] skip non existing resourceDirectory /Users/cmoullia/code/kie/onboarding/src/test/resources
[INFO] Invoking quarkus:3.8.2:generate-code-tests (default) @ onboarding
[INFO] Invoking compiler:3.10.1:testCompile (default-testCompile) @ onboarding
[INFO] Nothing to compile - all classes are up to date
Listening for transport dt_socket at address: 5005
2024-03-25 10:59:42,851 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2024-03-25 10:59:43,019 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.NoClassDefFoundError: io/quarkus/devconsole/spi/DevConsoleTemplateInfoBuildItem
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:534)
        at java.base/java.lang.Class.forName(Class.java:513)
        at io.quarkus.deployment.util.ServiceUtil.classesNamedIn(ServiceUtil.java:29)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:160)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:107)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:251)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:112)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:433)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:55)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: java.lang.ClassNotFoundException: io.quarkus.devconsole.spi.DevConsoleTemplateInfoBuildItem
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:518)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
        ... 16 more
```

**Comment by dmartinol** [comment]
Pls try the [latest version of the pom](https://github.com/parodos-dev/workflow-software-templates/blob/c5c62602838e4bd0f9b04b138b71983cecdeb6ef/scaffolder-templates/basic-workflow/skeleton/pom.xml#L11C3-L23C5) instead.

It should work but you need to update the sample `input.json` to:
```
{
  "onboarding__sub_schema__sample_data.json": {
    "sampleText": "Hello world!"
  }
}
```

**Comment by cmoulliard** [comment]
Many thanks. Problem is resolved :-)

![Screenshot 2024-03-26 at 10 39 38](https://github.com/parodos-dev/workflow-software-templates/assets/463790/1a82f5c8-8da7-4afa-8543-642607af17e0)
![Screenshot 2024-03-26 at 10 39 23](https://github.com/parodos-dev/workflow-software-templates/assets/463790/186c66c3-63ab-49a6-a262-aff45af5823e)
